// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC10zs_5aUEwcsXRLNQQexCTyqH9uYsnqs',
    appId: '1:1092982695441:web:aa2827b6d0e8e2fca733b0',
    messagingSenderId: '1092982695441',
    projectId: 'speedstar-prod-4c7c5',
    authDomain: 'speedstar-prod-4c7c5.firebaseapp.com',
    storageBucket: 'speedstar-prod-4c7c5.firebasestorage.app',
    measurementId: 'G-7J776NP96S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbgGPciw_z3b_4K3kqw5IIfCCzwDSviQ4',
    appId: '1:1092982695441:android:2cb45a47aed9ef5da733b0',
    messagingSenderId: '1092982695441',
    projectId: 'speedstar-prod-4c7c5',
    storageBucket: 'speedstar-prod-4c7c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0U7PsxceG-KqItAp55dWNq2JRdZjPdSE',
    appId: '1:1092982695441:ios:00e55b6ee0e287c2a733b0',
    messagingSenderId: '1092982695441',
    projectId: 'speedstar-prod-4c7c5',
    storageBucket: 'speedstar-prod-4c7c5.firebasestorage.app',
    androidClientId: '1092982695441-6jb7sf0b7c0a43c7o848krneav8u5mie.apps.googleusercontent.com',
    iosClientId: '1092982695441-hhe65p74u5uoqbh36bl3e3jmaf3dtmsi.apps.googleusercontent.com',
    iosBundleId: 'com.speedstar.courier',
  );
}
