// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrCx60bLuiz6Jxy59FLS9FDrnpGXk61TY',
    appId: '1:904679257048:web:4127af2462133830a5f8ad',
    messagingSenderId: '904679257048',
    projectId: 'speedstar-dev',
    authDomain: 'speedstar-dev.firebaseapp.com',
    storageBucket: 'speedstar-dev.firebasestorage.app',
    measurementId: 'G-5RS0BVKF4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDppu3x1GzC9_kmZ6AV4EKks8HjQiYqEpE',
    appId: '1:904679257048:android:8847f97cc91d3ac0a5f8ad',
    messagingSenderId: '904679257048',
    projectId: 'speedstar-dev',
    storageBucket: 'speedstar-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMqaEQayZDAULoc9s7NHgWWsXQMiMR06o',
    appId: '1:904679257048:ios:342ce1364456ccfda5f8ad',
    messagingSenderId: '904679257048',
    projectId: 'speedstar-dev',
    storageBucket: 'speedstar-dev.firebasestorage.app',
    androidClientId: '904679257048-cdkqfljgodknddvql60ua4tvv1uu87u6.apps.googleusercontent.com',
    iosClientId: '904679257048-7kr8r2kd81nq08u7thhjrkurrpca41bj.apps.googleusercontent.com',
    iosBundleId: 'com.speedstar.client',
  );
}